### PR TITLE
Issue fixed 2.4.1

### PR DESCRIPTION
**Pull request by jissereitsma**

### CODE REVIEW

**Comment by jissereitsma** [comment]
https://github.com/ho-nl/magento2-ReachDigital_TestFramework/issues/22

**Comment by paales** [comment]
Somehow I didn't notified of this PR (and your issue), changed some notification preferences and should be better now.

Looks good, have you had the chance to test this version on 2.3.x as well? We still have some projects running on that version.

Could you perhaps rebase and name the the commit something like: `feat: support for new overrides feature introduced in Magento 2.4.1` This way it automatically gets added to the release notes. (https://github.com/semantic-release/semantic-release#commit-message-format)

**Comment by jissereitsma** [comment]
Yes, this works still fine with Magento 2.3 as well - I'm still running that actively as well during development myself, plus in a custom CI chain. 

Instead of rebasing, I've added the feature to the CHANGELOG in my PR. Hope that's ok as well?

**Comment by paales** [comment]
@jissereitsma Good enough :) I'll add it to the release notes

**Comment by paales** [comment]
Available in the 1.4.0 release!

**Comment by jissereitsma** [comment]
Awesome, thanks!

**Pull request merged**
